# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(220, 300)
        MainWindow.setMinimumSize(QtCore.QSize(220, 300))
        MainWindow.setMaximumSize(QtCore.QSize(220, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 181, 231))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fpln = QtWidgets.QPushButton(self.widget)
        self.fpln.setObjectName("FPLN")
        self.verticalLayout.addWidget(self.fpln)
        self.ReadyButton = QtWidgets.QPushButton(self.widget)
        self.ReadyButton.setObjectName("ReadyButton")
        self.verticalLayout.addWidget(self.ReadyButton)
        self.InitButton = QtWidgets.QPushButton(self.widget)
        self.InitButton.setObjectName("InitButton")
        self.verticalLayout.addWidget(self.InitButton)
        self.ModifButton = QtWidgets.QPushButton(self.widget)
        self.ModifButton.setObjectName("ModifButton")
        self.verticalLayout.addWidget(self.ModifButton)
        self.RouteButton = QtWidgets.QPushButton(self.widget)
        self.RouteButton.setObjectName("RouteButton")
        self.verticalLayout.addWidget(self.RouteButton)
        self.quit = QtWidgets.QPushButton(self.widget)
        self.quit.setObjectName("QuitButton")
        self.verticalLayout.addWidget(self.quit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 220, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.fpln.setText(_translate("MainWindow", "FPLN"))
        self.ReadyButton.setText(_translate("MainWindow", "READY"))
        self.InitButton.setText(_translate("MainWindow", "INIT"))
        self.ModifButton.setText(_translate("MainWindow", "MODIF"))
        self.RouteButton.setText(_translate("MainWindow", "ROUTE"))
        self.quit.setText(_translate("MainWindow", "QUIT"))



